typography_spectrum: 0.61036
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9806
  lightness: 0.496621
  rhythmicContrast: 0.242007
  saturation: 0.862363
opengraph: {}
layout_spectrum: 1
analytics: {}
name: Aria
cta: {}
title: Aria
purpose: {}
